name: Bug report
description: Something is not working correctly.
labels: "bug"

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: >-
        A clear and concise description of what the bug is, including the 
        expected behaviour and what has gone wrong.
        
        Please include screenshots, if applicable.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce
      description: >-
        Please provide steps to reproduce this bug, with the smallest possible
        set of source files.
      placeholder: |
        ""
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Environment info
        
  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here, for example:
        
        * Any other tools used (Browser, TeX, etc) with versions
        * Reference to another issue or pull request
        * URL to some external resource